### ISSUE TITLE
how to cancel Efect

### ISSUE THREAD

**Issue by mohamad-mehdi** [pixxelfactory/jInvertScroll#4]
hi !
i want to cancel all of the efects even page scrollbar and all of events by clicking on something
is it possible ?

**Comment by pixxelfactory** [comment]
Hi,

yes, you can, first create the element on wich to click on, for example:
<button id="disable">Disable scroll</button>

then, in your javascript block, add a click event to the button and remove the scroll and resize event from the window-element:

$('#disable').on('click', ,function(e) {
  e.preventDefault(); // only needed if element is a link, submit button or similar
  $(window).off('scroll resize');
});

If you want to re-enable it, you have to modify the plugin, since you need to re-bind the scroll and resize event to the scroll procedure.

Cheers
pixxelfactory
