### ISSUE TITLE
Slow performance on ipad

### ISSUE THREAD

**Issue by smigielski** [pixxelfactory/jInvertScroll#9]
Very slow performance on ipad and mobile devices. Can we do something with it?

**Comment by christoshrousis** [comment]
I had to resort to disabling on iPad and below as it was unusable :( I have kept it for my desktop version because I really liked this plugin.

**Comment by pixxelfactory** [comment]
Hi,
mobile devices are limited due to their energy-saving features.
I suggest not to use it on iPad or iPhone anyways because of usability-issues (since you don't controll the scroll via the mouse but via physical swipe, it is awkward to swipe downwards while the content scrolls sideways.)
But we will look into performance optimization as soon as we have one little moment of time.

**Comment by pixxelfactory** [comment]
Hmmm... i don't think so, because it would have to enlarge the container
and everything in it.
Maybe you can try to rewrite the plugin so that it recalculates the
width everytime you add new content
and load it everytime you reach the end?

Regards

Am 30.07.14 12:21, schrieb chrismackie:
